#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=24        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=5   \
                 padding_right=5  \
                 color=$TRANSPARENT

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:11.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:11.0" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=3            \
                     background.height=16                  \
                     padding_left=2                        \
                     padding_right=2                       \
                     label.padding_left=2                  \
                     label.padding_right=5                 \
                     icon.padding_left=5                   \
                     icon.padding_right=2

# -- Left Side Items --
source $ITEM_DIR/aerospace_workspaces.sh
source $ITEM_DIR/separator.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
sketchybar --update